# Generated by Django 4.1.4 on 2022-12-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('dataNascimento', models.DateField()),
                ('nRegistro', models.CharField(max_length=50)),
                ('contato', models.CharField(max_length=20)),
                ('pressaoArterial', models.CharField(max_length=10)),
                ('temperatura', models.CharField(max_length=10)),
                ('principaisSintomas', models.CharField(max_length=1000)),
                ('dataInternacao', models.DateField()),
                ('dataAlta', models.DateField()),
                ('medicacao', models.CharField(max_length=1000)),
                ('observacoesComplementares', models.CharField(max_length=1000)),
            ],
        ),
    ]
