# Generated by Django 4.1.4 on 2022-12-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuario',
            name='medicacao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='observacoesComplementares',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='principaisSintomas',
            field=models.TextField(),
        ),
    ]
