# Generated by Django 4.1.4 on 2022-12-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0003_alter_prontuario_contato_alter_prontuario_dataalta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prontuario',
            name='nRegistro',
        ),
    ]
